EWPP-2910: Update to PHP 8.1 and D9.4.
openeuropa/oe_editorial pull request #117
Opened 2023-01-11 12:39 UTC by 22Alexandra

2023-01-17 15:49 UTC, sergepavle commented
There are `modules/oe_editorial_corporate_workflow/tests/modules/oe_editorial_corporate_workflow_test/oe_editorial_corporate_workflow_test.info.yml` not yet updated core_version_requirement.

2023-01-17 15:51 UTC, sergepavle submitted a review, later dismissed

2023-01-18 09:30 UTC, nagyad requested changes

2023-01-18 09:30 UTC, nagyad commented on composer.json
> +        "ec-europa/oe-poetry-client": "dev-EWPP-2948",
Change one the oe-poetry-client PR is merged.

2023-01-18 15:05 UTC, nagyad approved these changes

2023-01-18 15:27 UTC, sergepavle approved these changes

2023-01-18 15:29 UTC, merged